Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
APP:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  DefaultContextTimeout: 72
  UploadSavePath: storage/uploads
  UploadServerURL: http://127.0.0.1:8080/static
  UploadImageMAxSize: 5 # MB
  UploadImageAllowExts:
    - .jpg
    - .jepg
    - .png
Database:
  DBType: mysql
  Username: root
  Password: YBpJEmyw2snGj9!
  Host: cdb-gbwa3hlu.cd.tencentcdb.com
  Port: 10086
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
JWT:
  Secret: JarvisZuo
  Issuer: blog-service
  Expire: 7200
Email:
  Host: mail.zuojiaxun.cn
  Port: 465
  UserName: no-reply@zuojiaxun.cn
  PassWord: A3SZF`6Tn5
  IsSSL: true
  From: no-reply@zuojiaxun.cn
  To:
    - jasonleft@qq.com
